### ISSUE TITLE
Top nav bar font style

### ISSUE THREAD

**Issue by dcgrigsby** [WildflowerSchools/website-qa#3]
Top nav bar font should be 13px, font weight 600.

<img width="233" alt="screen shot 2017-11-14 at 9 43 59 am" src="https://user-images.githubusercontent.com/30864/32789020-6263432e-c920-11e7-824f-2ac17aaf6405.png">

**Comment by sassinator** [comment]
fixed on staging

**Comment by dcgrigsby** [comment]
still not the same

<img width="577" alt="screen_shot_2017-11-22_at_12_17_30_pm" src="https://user-images.githubusercontent.com/30864/33143353-41c70b68-cf7f-11e7-839a-b00f8e3b0f11.png">

**Comment by sassinator** [comment]
@dcgrigsby font on current site is Raleway (wee how the capital W) is different. I'm guessing that was a hold over from something else and that we should use Mr. Eaves Sans (since that is the font we are using every where else). We updated to be a version of Mr. Eaves that is close in weight. What do you think?

**Comment by dcgrigsby** [comment]
You did the right thing.  The other one was a mistake - mine.
