### ISSUE TITLE
Front page - three column area - image alignment

### ISSUE THREAD

**Issue by dcgrigsby** [WildflowerSchools/website-qa#9]
Images should be the same height so that the text lines up. 

<img width="763" alt="screen_shot_2017-11-14_at_10_34_35_am" src="https://user-images.githubusercontent.com/30864/32791967-d7a8c7a6-c927-11e7-951d-47cf540f6025.png">

Note, this was present in the live site, but - for whatever reason - isn't in the staging environment.

**Comment by sassinator** [comment]
Fixed on staging

**Comment by dcgrigsby** [comment]
Still broken

<img width="1017" alt="screen_shot_2017-11-22_at_12_19_53_pm" src="https://user-images.githubusercontent.com/30864/33143528-c602ecee-cf7f-11e7-9ff1-12bbaf2670a7.png">

**Comment by sassinator** [comment]
Just so you don't think I'm nuts, here's the screen cap I took the other day! 

![image](https://user-images.githubusercontent.com/6728316/33145512-4169fe12-cf86-11e7-857e-61bf8a3d5010.png)

But I see it's as you show now. Will look at it again...

**Comment by sassinator** [comment]
@dcgrigsby should be fixed now!
